"""Tests for conventional-commit parsing, grouping, and rendering."""

from __future__ import annotations

import unittest
from pathlib import Path

from relnote.format import (
    classify,
    group_commits,
    is_bot,
    looks_like_secret,
    notes_from_rows,
    parse_coauthors,
    parse_conventional,
    render,
    select,
)

# Fake token used only to prove we drop it. Must never appear in sample output.
_FAKE_GITHUB_TOKEN = "ghp_" + ("a" * 36)


def synthetic_commits() -> list[dict]:
    """A fictional harbor CLI history. Not taken from any real repository."""
    return [
        {
            "subject": "feat!: replace JSON store with SQLite",
            "body": (
                "BREAKING CHANGE: harbor dump --json now writes NDJSON.\n\n"
                "Co-authored-by: Sam Rivera <sam@example.com>\n"
            ),
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "short_hash": "a11a11a",
        },
        {
            "subject": "feat(cli): add harbor sync --dry-run",
            "body": "",
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "short_hash": "b22b22b",
        },
        {
            "subject": "feat: import Netscape bookmark files",
            "body": "",
            "author_name": "Grace Hopper",
            "author_email": "grace@example.com",
            "short_hash": "c33c33c",
        },
        {
            "subject": "fix: do not drop tags that contain commas",
            "body": "",
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "short_hash": "d44d44d",
        },
        {
            "subject": "fix(parser): accept single-quoted hrefs",
            "body": "Co-authored-by: Grace Hopper <grace@example.com>\n",
            "author_name": "Sam Rivera",
            "author_email": "sam@example.com",
            "short_hash": "e55e55e",
        },
        {
            "subject": "docs: document the XBEL importer",
            "body": "",
            "author_name": "Grace Hopper",
            "author_email": "grace@example.com",
            "short_hash": "f66f66f",
        },
        {
            "subject": "chore: bump actions/checkout",
            "body": "",
            "author_name": "dependabot[bot]",
            "author_email": "49699333+dependabot[bot]@users.noreply.github.com",
            "short_hash": "111aaaa",
        },
        {
            "subject": "chore(deps): update rust crate serde",
            "body": "",
            "author_name": "renovate[bot]",
            "author_email": "renovate@example.com",
            "short_hash": "222bbbb",
        },
        {
            "subject": "refactor: split store module from cli",
            "body": "",
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "short_hash": "333cccc",
        },
        {
            "subject": f"fix: rotate leaked token {_FAKE_GITHUB_TOKEN}",
            "body": "",
            "author_name": "Ada Lovelace",
            "author_email": "ada@example.com",
            "short_hash": "444dddd",
        },
        {
            "subject": "Initial floating-window layout for the TUI",
            "body": "",
            "author_name": "Sam Rivera",
            "author_email": "sam@example.com",
            "short_hash": "555eeee",
        },
    ]


def write_sample(path: str | Path) -> str:
    """Render the synthetic list to a GitHub-flavored sample file."""
    text = notes_from_rows(
        synthetic_commits(),
        no_bots=True,
        format="github",
        since="v0.9.0",
        until="v1.0.0",
    )
    header = (
        "# Example output (synthetic)\n"
        "\n"
        "Generated by relnote from a fake commit list for a fictional CLI\n"
        "called harbor. Not taken from any real repository.\n"
        "\n"
        "---\n"
        "\n"
    )
    Path(path).write_text(header + text, encoding="utf-8")
    return text


class ParseConventionalTests(unittest.TestCase):
    def test_feat(self) -> None:
        parsed = parse_conventional("feat: add widgets")
        self.assertIsNotNone(parsed)
        assert parsed is not None
        self.assertEqual(parsed["type"], "feat")
        self.assertIsNone(parsed["scope"])
        self.assertFalse(parsed["breaking"])
        self.assertEqual(parsed["description"], "add widgets")

    def test_feat_scope(self) -> None:
        parsed = parse_conventional("feat(cli): add --max")
        self.assertIsNotNone(parsed)
        assert parsed is not None
        self.assertEqual(parsed["scope"], "cli")
        self.assertEqual(parsed["description"], "add --max")

    def test_feat_bang(self) -> None:
        parsed = parse_conventional("feat!: drop v1")
        self.assertIsNotNone(parsed)
        assert parsed is not None
        self.assertTrue(parsed["breaking"])
        self.assertEqual(parsed["description"], "drop v1")

    def test_feat_scope_bang(self) -> None:
        parsed = parse_conventional("feat(api)!: remove /v1")
        self.assertIsNotNone(parsed)
        assert parsed is not None
        self.assertEqual(parsed["type"], "feat")
        self.assertEqual(parsed["scope"], "api")
        self.assertTrue(parsed["breaking"])

    def test_fix_case_insensitive(self) -> None:
        parsed = parse_conventional("FIX(parser): accept quotes")
        self.assertIsNotNone(parsed)
        assert parsed is not None
        self.assertEqual(parsed["type"], "fix")

    def test_non_conventional(self) -> None:
        self.assertIsNone(parse_conventional("Initial floating-window layout"))
        self.assertIsNone(parse_conventional("feature: not a real type"))
        self.assertIsNone(parse_conventional("feat add missing colon"))


class ClassifyTests(unittest.TestCase):
    def test_feat_is_features(self) -> None:
        item = classify("feat: add widgets")
        self.assertEqual(item.category, "features")
        self.assertEqual(item.description, "add widgets")

    def test_fix_is_fixes(self) -> None:
        item = classify("fix: handle empty range")
        self.assertEqual(item.category, "fixes")

    def test_bang_is_breaking(self) -> None:
        item = classify("feat!: drop Python 3.9")
        self.assertEqual(item.category, "breaking")

    def test_breaking_change_footer(self) -> None:
        item = classify(
            "feat: new store",
            "Details here.\n\nBREAKING CHANGE: dump --json writes NDJSON.\n",
        )
        self.assertEqual(item.category, "breaking")
        self.assertEqual(item.breaking_note, "dump --json writes NDJSON.")

    def test_breaking_change_hyphen_footer(self) -> None:
        item = classify("fix: headers", "BREAKING-CHANGE: auth header required")
        self.assertEqual(item.category, "breaking")
        self.assertEqual(item.breaking_note, "auth header required")

    def test_chore_is_other(self) -> None:
        item = classify("chore: bump actions")
        self.assertEqual(item.category, "other")
        self.assertEqual(item.ctype, "chore")

    def test_plain_subject_is_other(self) -> None:
        item = classify("Initial floating-window layout for the TUI")
        self.assertEqual(item.category, "other")
        self.assertEqual(
            item.description, "Initial floating-window layout for the TUI"
        )
        self.assertIsNone(item.ctype)


class GroupingTests(unittest.TestCase):
    def test_buckets_and_order(self) -> None:
        items = [
            classify("chore: x"),
            classify("feat: y"),
            classify("fix: z"),
            classify("feat!: w"),
        ]
        grouped = group_commits(items)
        self.assertEqual([i.description for i in grouped["breaking"]], ["w"])
        self.assertEqual([i.description for i in grouped["features"]], ["y"])
        self.assertEqual([i.description for i in grouped["fixes"]], ["z"])
        self.assertEqual([i.description for i in grouped["other"]], ["x"])
        self.assertEqual(
            list(grouped.keys()),
            ["breaking", "features", "fixes", "other"],
        )

    def test_render_github_section_order(self) -> None:
        text = notes_from_rows(
            [
                {"subject": "chore: noise", "short_hash": "aaa"},
                {"subject": "feat: shine", "short_hash": "bbb"},
                {"subject": "fix: dent", "short_hash": "ccc"},
                {"subject": "feat!: boom", "short_hash": "ddd"},
            ]
        )
        breaking = text.index("### Breaking")
        features = text.index("### Features")
        fixes = text.index("### Fixes")
        other = text.index("### Other")
        self.assertLess(breaking, features)
        self.assertLess(features, fixes)
        self.assertLess(fixes, other)
        self.assertIn("## What's changed", text)
        self.assertIn("shine (`bbb`)", text)

    def test_render_plain_has_no_hashes_as_markdown(self) -> None:
        text = notes_from_rows(
            [{"subject": "feat: shine", "short_hash": "bbb"}],
            format="plain",
        )
        self.assertIn("shine (bbb)", text)
        self.assertNotIn("(`bbb`)", text)
        self.assertNotIn("###", text)


class CoauthorTests(unittest.TestCase):
    def test_parse_coauthors(self) -> None:
        body = (
            "Some explanation.\n\n"
            "Co-authored-by: Grace Hopper <grace@example.com>\n"
            "Co-authored-by: Sam Rivera <sam@example.com>\n"
        )
        pairs = parse_coauthors(body)
        self.assertEqual(
            pairs,
            [
                ("Grace Hopper", "grace@example.com"),
                ("Sam Rivera", "sam@example.com"),
            ],
        )

    def test_does_not_invent_authors(self) -> None:
        item = classify("feat: solo work", author_name="Ada Lovelace")
        self.assertEqual(item.authors, ["Ada Lovelace"])
        self.assertEqual(parse_coauthors(""), [])
        self.assertEqual(parse_coauthors("Reviewed-by: Someone <x@y.z>"), [])

    def test_authors_dedupe_primary(self) -> None:
        item = classify(
            "feat: together",
            "Co-authored-by: Ada Lovelace <ada@example.com>\n",
            author_name="Ada Lovelace",
        )
        self.assertEqual(item.authors, ["Ada Lovelace"])


class BotAndSecretTests(unittest.TestCase):
    def test_bot_markers(self) -> None:
        self.assertTrue(is_bot(author_name="dependabot[bot]"))
        self.assertTrue(is_bot(author_email="renovate@example.com"))
        self.assertTrue(is_bot(author_name="github-actions[bot]"))
        self.assertFalse(is_bot(author_name="Ada Lovelace", subject="feat: add bots list"))

    def test_no_bots_drops_them(self) -> None:
        items = [
            classify("chore: bump", author_name="dependabot[bot]"),
            classify("feat: real work", author_name="Ada"),
        ]
        chosen = select(items, no_bots=True)
        self.assertEqual([i.description for i in chosen], ["real work"])

    def test_secret_subject_is_dropped(self) -> None:
        item = classify(f"fix: rotate {_FAKE_GITHUB_TOKEN}")
        self.assertTrue(item.secret)
        self.assertTrue(looks_like_secret(item.description) or looks_like_secret(f"fix: rotate {_FAKE_GITHUB_TOKEN}"))
        self.assertEqual(select([item]), [])

    def test_render_never_prints_token(self) -> None:
        text = notes_from_rows(synthetic_commits(), no_bots=True)
        self.assertNotIn(_FAKE_GITHUB_TOKEN, text)
        self.assertNotIn("ghp_", text)

    def test_max_limit(self) -> None:
        rows = [{"subject": f"feat: item {i}"} for i in range(10)]
        text = notes_from_rows(rows, max_n=3)
        self.assertEqual(text.count("- item"), 3)

    def test_empty_select_renders_empty(self) -> None:
        self.assertEqual(select([]), [])
        self.assertEqual(render(group_commits([])), "")


class SampleHelperTests(unittest.TestCase):
    def test_synthetic_sample_shape(self) -> None:
        text = notes_from_rows(
            synthetic_commits(),
            no_bots=True,
            since="v0.9.0",
            until="v1.0.0",
        )
        self.assertIn("### Breaking", text)
        self.assertIn("### Features", text)
        self.assertIn("### Fixes", text)
        self.assertIn("### Other", text)
        self.assertIn("Sam Rivera", text)
        self.assertIn("Grace Hopper", text)
        self.assertNotIn("dependabot", text)
        self.assertNotIn("renovate", text)
        self.assertIn("v0.9.0", text)
        self.assertIn("omitted", text)


if __name__ == "__main__":
    unittest.main()
